[uwsgi]
# 1: uwsgi直接作为web服务器时，使用的ip和端口
# http = 127.0.0.1:8000
socket = 127.0.0.1:8001
# 2:指定项目的目录
chdir = /public/softwares/SLAM_rice/web
# 3: 指定项目中的wsgi.py所在的目录:(这个文件是usgi的启动入口)
wsgi-file = app.py
callable = app  
# 4：指定uwsgi工作的进程数
processes = 8
# 5: 指定工作的每个进程下的线程数
threads = 12
vacuum = true
# 6: 主进程的配置
master = true
pidfile = uwsgi.pid
# 7: 指定uwsgi的日志文件
daemonize =/public/softwares/SLAM_rice/web/uwsgi.log
buffer-size = 65536
static-map = /static=/public/softwares/SLAM _rice/web/static
